### ISSUE TITLE
[1pt] Fix remote_control_test for tarantool 2.4+

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1058]
Tarantool box.error API was significantly refactored in scope of https://github.com/tarantool/tarantool/issues/4398 and now cartridge tests fail:

```lua
local ok, err = pcall(conn.eval, conn,
    'error("ScriptError", 0)'
)
t.assert_not(ok)
t.assert_equals(type(err), 'cdata')
t.assert_equals(err.code, box.error.PROC_LUA) -- expected: 32, actual: nil
```

https://gitlab.com/tarantool/cartridge/-/jobs/746467482

**Comment by LeonidVas** [comment]
The problem is that before, all errors were converted to ClientError after being passed to the client side, and an error code was added to them. Now the error does not change type after transmission, and if it does not derived from ClientError, a code field will be missing. I believe that it is ok leaving it as is, especially since I haven't found a contract according to which we guarantee the presence of a code field on the client side for all types of error.
