### ISSUE TITLE
Register services in consul

### ISSUE THREAD

**Issue by knazarov** [tarantool/cartridge#1088]
When working with consul as config storage, we can register routers and storages there as services, in addition to just storing topology. This will allow other external services to use consul as service registry to access the routers.

**Comment by rosik** [comment]
We don't support consul yet, and not going to do in the nearest future.

**Comment by Kasen** [comment]
I suggest splitting this request into two parts.
1. Some of our customers have consul in their infrastructure. These customers want to use it instead of stateboard or etcd.
2. Consul provides a service discovery system. This is useful to organize server mesh, monitoring, log shipping, etc. Our customers in one big bank want to use it. It may be realised in custom roles, but it doesn't conveniently if we use some different cartridge apps. In this part, I suggest registering tarantool instances as consul services with roles as tags.

**Comment by filonenko-mikhail** [comment]
Definetely usefule but this time gently closing. Need more precise user story.
