### ISSUE TITLE
[4pt] Redesign role API

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#116]
In GitLab by @rosik on Jun 4, 2019, 18:53

There are several wishes/issues with current role API:

* `validate_config` is called for every role on every instance, which is redundant (and may even be harmful, see #107)
* `apply_config` doesn't distinguish different cases such as topology change / failover / config upload. See #85 
* Callbacks names are bad. Today we've encountered a name clash: a role used `stop` function for RPC purposes, which collides with stopping role itself.

**Comment by sharonovd** [comment]
In GitLab by @rosik on Jun 4, 2019, 19:13

changed the description

**Comment by rosik** [comment]
Related to #859

**Comment by Steap2448** [comment]
Current failover algorithm doesn't take ``OperationError`` during ``apply_config`` seriously. If error occurs there are error logs but that's about it. Eventually instance will enter ``RolesConfigured`` state despite it all. Such scenario is undesirable and should be fixed. 

The first step would be enriching ``opts`` argument of role's ``apply_config`` with additional parameters (e.g. instance uuid, advertise uri, leaders order, etc). They can be useful for tracking role relevant changes in clusterwide config. When there is none ``apply_config`` can be skipped and potential ``OperationError`` will not occur. Moreover, additional parameters may come in handy for roles managment and development.

However, it will not affect ``vshard-router`` and ``vshard-storage`` because both of them depend on cluster topology, especially leaders order, which is always changed by failover.

**Comment by filonenko-mikhail** [comment]
So, this time we have to think about role callback management more precisely. Feel free to reopen.
