### ISSUE TITLE
[2pt] Investigate misterious "Connection timed out" error

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1286]
On brand new Cartridge 2.4.0 role validate_config fails if config is invalid due to config error leads an NetboxConnectionError with ConnectionTimeout while on 2.3.0 it returns meaningfull GraphQL error.

Steps to reproduce:
1. Setup new app with metrics 0.7.0
2. Run it
3. Go to Code section and create metrics.yml with valid yaml but some spell error in format
4. Press Apply

On Cartridge 2.3 you will get:
![image](https://user-images.githubusercontent.com/17825302/109757058-176d1f80-7bfa-11eb-9b5c-987cd3e775a6.png)

On Cartridge 2.4 you will get:
![image](https://user-images.githubusercontent.com/17825302/109757076-26ec6880-7bfa-11eb-9d92-3d40305de6b0.png)

**Comment by rosik** [comment]
Despite it's not related to the config validation, the "Connection timed out" error should be investigated further.

Steps to reproduce:

1. Bootsrap a cluster
2. break the `validate_config` to throw an error.
3. Restart the cluster, it'll enter "InitError" state
4. Change the code and try to apply.

**Comment by Steap2448** [comment]
'''Connection timed out'' error is caused by ``remote-control``. It is [bind](https://github.com/tarantool/cartridge/blob/83a08a0be09625525c48390759cedddcd28dd438/cartridge/confapplier.lua#L583) to a port prior to ``InitError`` and, as a result, never stopped. Moreover, if config is [present](https://github.com/tarantool/cartridge/blob/83a08a0be09625525c48390759cedddcd28dd438/cartridge/confapplier.lua#L616) then ``remote-control`` isn't accepting connections (it is expecting a quick ``box.cfg{listen=...}``) and connections [hang](https://github.com/tarantool/cartridge/blob/83a08a0be09625525c48390759cedddcd28dd438/cartridge/remote-control.lua#L302) until timeout.
