### ISSUE TITLE
Hotreload: Add 'reloadable' option to cartridge role

### ISSUE THREAD

**Issue by no1seman** [tarantool/cartridge#1329]
Since hotreloadble Cratirge Role must include some special mechanics to be successfully reloaded in runtime but most of existing roles doesn't have it - need to add an `reloadable` (`boolean`) option to role with the foolowing logic: if role may be roaded it's `reloadable` option must be true, in any other cases (false/nil) cartridge shouldn't reload the role. To make this change backward compatible simply need to add global option to cartridge.cfg - `reload_strict` false/nil by default which means all roles may be reloaded, but if `reload_strict` is true then can be reloaded only roles with option reloadable == true.

**Comment by akudiyar** [comment]
I think this option may be derived from presence of an explicit `relaod` role API method, which will indicate that the authors of this role prepared it for hot-reload. Seems that any automatic reload mechanism for user roles will lead to unknown errors and it's better to force the user to implement reload explicitly.

**Comment by rosik** [comment]
Code reload isn't an operation one can do for a single module. Modules create closures, and you can't offload them one by one. Instead, think of it as restoring the global state to some earlier point in time. There're only two options available - either reload them all or don't reload at all.

> but most of existing roles doesn't have it

It was fixed in the last few months and I hope you don't need this feature anymore.
