### ISSUE TITLE
Link from one node webui to other

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#1680]
## Idea

The Idea is to make link from one webui node to another. Here (not instead)
![telegram-cloud-document-2-5359395689577058785](https://user-images.githubusercontent.com/370551/147603933-367f471a-0c5b-4593-9045-e81d019c9917.jpg)

Consider to make additional link button (or anything else) to make jump to other node weui.

http:// + advertise-uri + : + web_port + webui_prefix

**Comment by R-omk** [comment]
Usually access to admin interfaces is hidden behind a proxy, since there is no direct access to hosts. In such cases, it can be used the _base path_ and a properly configured proxy server.

Example:
`https://some-fixed-domain-or-ip/cluster1/rs1/host1/`

But this requires that the web application can work with an arbitrary _base path_, and not just with the root one ( `/`).

**Comment by kyukhin** [comment]
Won't be implemented.
