### ISSUE TITLE
Expelled instance has access to cartridge.rpc

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/cartridge#1726]
I noticed that if a instance is expelled out of the cluster, it will still be able to make `cartridge.rpc` calls, and maybe something else.

This is very bad.

**Comment by yngvar-antonsson** [comment]
Now we don't have any reliable way to fix it:
- We can't notify instance that it's expelled (because it could be dead or stopped)
- Expelled instance think that it's old cluster is unhealthy and that cluster configuration is broken. Config mismatch check can't be done with the same reason that was in #1588. 
- net.box connection doesn't authenticate by instance uuid, so we can't ban net.box calls from the expelled instances.
- We could pass instance uuid in rpc call and check it each time we perform rpc calls, but it will slow calls.

So, I'll close this issue with test and advise to stop expelled instances.
