### ISSUE TITLE
Refactor *_dir options handling

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#189]
Nowadays there are 5 different options in cartridge + tarantool:

1. `workdir` (in cartridge.cfg) - to store everything including his clusterwide config.
2. `work_dir` (in box.cfg) - to change PWD
3. `wal_dir` (in box.cfg) - to store *.xlog files
4. `memtx_dir` (in box.cfg) - to store *.snap files
5. `vinyl_dir` (in box.cfg) - to store vinyl stuff

Cartridge should stop using his own `workdir` param and be more friendly to tarantool configuration api:

1. `workdir` param should be deprecated. `work_dir` should be used instead. Cartridge will pass it to box.cfg, so it's gonna be used for `fio.chdir()`.
1. clusterwide config should be stored in `work_dir`.
1. None of wal/memtx/vinyl dirs should never be overriden.
1. Bootstrapping from snapshot should respect `memtx_dir` and search snapshots there.

**Comment by rosik** [comment]
@knazarov please, comment the proposal.

**Comment by knazarov** [comment]
OK

**Comment by opomuc** [comment]
Could be related to https://github.com/tarantool/cartridge-cli/issues/46

**Comment by HustonMmmavr** [comment]
I guess we don’t need to support box.work_dir option because in our case this option is useless: 
- we still store `workdir` at confapplier variables for backward compatibility 
- `box.cfg{}` implicitly runs chdir to `box.work_dir` and because of that we loose current working directory where we have started cartridge, so all relative paths to files that user created will be broken and also we have to call `package.setsearchroot()` to resolve modules requirements. 

I think we need to support only `box{memtx_dir, vinyl_dir, was_dir}` and deprecate using `box{work_dir}`
