### ISSUE TITLE
Corner case for slash in graphql does not work

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#238]
```
mutation {
  something(arg:"\\")
}
```

failed with error: syntax parse error

**Comment by olegrok** [comment]
The problem is in 
https://github.com/tarantool/cartridge/blob/d7382018523ca95da738535cc61c6be0c7c3d6be/cartridge/graphql/parse.lua#L253

I assume the logic is following:
* We want to found a string that starts with `"`
* Then match some string that could contain escaped bracket `\"` or  one of {`"`,`\n`}
* Such patten should ends with `"`

I solve a problem when string starts with `\\`, the diff is quite simple:

```diff
@@ -55,7 +55,7 @@ local cEnum = simpleValue('enum')
 local cString = function(value)
   return {
     kind = 'string',
-    value = value:gsub('\\"', '"')
+    value = value:gsub('\\"', '"'):gsub('\\\\', '\\')
   }
 end
```

```lua
tarantool> require('graphql.parse')('{ value(value: "\test") }')
---
- definitions:
  - operation: query
    selectionSet:
      selections:
      - arguments:
        - value:
            value: "\test"
            kind: string
          name:
            value: value
            kind: name
          kind: argument
        name:
          value: value
          kind: name
        kind: field
      kind: selectionSet
    kind: operation
  kind: document
...
```

But such approach fails for `\` at the end of string. I assume because it's try to finish parsing then found `\"` because of the second point
