### ISSUE TITLE
Support separate files in cluster-wide config (aka server extensions)

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#329]
@knazarov said:
> The code that is deployed should be a regular set of files. We shouldn't have any special treatment for them, even for file types. If the user wants to deploy yaml files along with the code -- let them do so.

Related to #320

**Comment by rosik** [comment]
### RFC

Clusterwide configuration is more than just a lua table.
It's an object in terms of OOP paradigm.

On filesystem clusterwide config is represented by a file tree.

In Lua it's represented as a table which holds
both plaintext files content and unmarshalled lua tables.

### Example

```text
config/
├── topology.yml
├── vshard.yml
├── schema.yml
├── extensions/
│   ├── foo.lua
│   ├── bar.yml
│   ├── buzz
│   └── bar
│       └── bar
└── auth.yml
```

```lua
cwcfg = {
  _plaintext = {
    -- represents file content on disk
    -- empty directories can't be kept
    ['topology.yml'] = "...",
    ['vshard.yml'] = "...",
    ['auth.yml'] = "...",
    ['extensions/foo.lua'] = "...",
    ['extensions/bar.yml'] = "...",
    ['extensions/buzz'] = "...",
  },
  _luatables = setmetatable({
    ['topology.yml'] = {...},
    ['vshard.yml'] = {...},
    ['auth.yml'] = {...},
    ['extensions/bar.yml'] = {...},
    ['extensions/foo.lua'] = string,
    ['extensions/buzz'] = string,
  }, {
    __newindex = error('table is readonly'),
    __index = function(_luatables, section_name)
      if _luatables[section_name .. '.yml'] ~= nil then
        -- issue deprecation warning and return it
      end
    end,
  }),
}
```

* `set_plaintext` -- assign `_plaintext[section]`.
  To avoid ambiguity setting a section is prohibited
  if `section.yml` already exitsts.
* `get_plaintext` -- return `_plaintext[section]`
* `get_readonly` -- returns `_luatables[section]` (implies yaml.decode)
* `get_deepcopy` -- similar to `get_readonly`, but deepcopy

### Format conversion and preserving backward compatibility

Cartridge still can read old format, but saves only the new one.

#### Loading old format

* If section content is a string, write it to the corresponding file as is.
* Otherwise do `yaml.encode()` and append `.yml` extension to it's name.

#### What does the patch_clusterwide do?

To be discussed
