### ISSUE TITLE
Show warning instead of memory usage indicator with high value of quota_used_ratio

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/cartridge#374]
We got a situation where memory indicator is green but the memory allocation fails by reason of high memory fragmentation. 

See: https://www.tarantool.io/en/doc/1.10/book/box/box_slab/

**Comment by rosik** [comment]
N.B.: Current frontend implementation is of indicator is here: https://github.com/tarantool/cartridge/blob/f4bef7225977e544a158b5d66bae8116d995c49e/webui/src/components/ReplicasetServerListItem.js#L190

**Comment by olegrok** [comment]
I want to refer to this issue - https://github.com/tarantool/doc/issues/421

In UI I see it as an icon here: ![image](https://user-images.githubusercontent.com/8830475/77537298-e2673180-6eae-11ea-9dba-c1143f38cca2.png)

⚠️ - in case of warning low fragmentation.
❌ - in case of high fragmentation.
And then user hovers the cursor to this label it see the message "Warning: Your memory is (highly) fragmented"

> So you really run out of memory when all three variables are close to 100%: items_used_ratio > 0.9 and arena_used_ratio > 0.9 and quota_used_ratio is > 0.9

This is a critical issue.

My suggestion is to show warn in case when these parameters are higher 0.6.

**Comment by rosik** [comment]
So, in other words, memory indicator coloring remains unchanged, but supplemented with additional icon, isn't it?

```
if arena_used_ratio > 0.9
and quota_used_ratio > 0.9
and items_used_ratio > 0.9
then
    -- critical icon
elseif arena_used_ratio > 0.9
and quota_used_ratio > 0.9
and items_used_ratio > 0.6
    -- warning icon
else
    -- normal icon
end

```

**Comment by olegrok** [comment]
> So, in other words, memory indicator coloring remains unchanged, but supplemented with additional icon, isn't it?

Yes, I suggest stay memory indicator as is.

For a warning icon "arena_used_ratio" and "quota_used_ratio" should be greater 0.6, not 0.9.

I try to describe that relation `arena_used / quota_size` means. According - http://kostja.github.io/misc/2017/02/17/tarantool-memory.html.

Quota is an object that limits a memory that tarantool can consume. In other words, `quota_size` is a memory limit. `arena_used ` is the efficient memory used for storing tuples and indexes together (omitting allocated, but currently free slabs). This metric indicates that we use all available memory (is not completely exact, because there is another parameter - `quota_used` that considers "allocated, but currently free slabs").
And it's possible situation when you have frequent inserts and deletions and as result have highly fragmentized memory that stores little amount of data.

And as for me it's quite intuitive to show for user amount of used memory as a bar.
