### ISSUE TITLE
Consider to use fibered handlers for every remote-control call/eval

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/cartridge#386]
There is case when we use remote-control connection and try to make two call.
The first call use long wait fiber.sleep(LARGE_VALUE)
The second call waits while first call returns.

Could you please consider to make separate fiber for every eval/call such as in the built-in netbox.

**Comment by rosik** [comment]
This behavior is planned to make the code simpler, and it's even mentioned in tests: https://github.com/tarantool/cartridge/blob/aa1d2b4fe6b00146cd42b74ae2b0fbb3f6e73b64/test/unit/remote_control_test.lua#L539-L565

I doubt parallel requests can be useful before the instance is bootstrapped. And afterwards full-featured iproto is available. There was another issue: remote-control connections were mistakenly cached even after bootstrap, but it was fixed with #387.
