### ISSUE TITLE
GraphQL: Add http port field to server graphql type

### ISSUE THREAD

**Issue by RunsFor** [tarantool/cartridge#622]
Following graphql query let me know binary port of each instance in a cluster:

``` grapqhl
{
  servers {
    boxinfo {
      general {
        listen
        # http_port # needed
      }
    }
  }
}
```

Each instance may have slightly different graphql API, so I want to query a particular instance. For this I need to be able to get its http port used to handle graphql requests

**Comment by knazarov** [comment]
i suggest to add this as part of cluster information API

**Comment by rosik** [comment]
I've thought about it for a while. We can add it to boxinfo, but it's almost useless there: boxinfo is only displayed (and queried) within server details dialog. But we can't query it as part of cluster information, because it's not available without RPC. Whe will try to resolve this issue in context of #660 later.

**Comment by rosik** [comment]
As a quick workaround I can offer to add it in boxinfo (with all its inconveniences). It's better then nothing.
