### ISSUE TITLE
RFC: Describe a way how to ship, maintain and deploy stateboard.lua

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#714]
Related issue - https://github.com/tarantool/cartridge-cli/issues/187

But since it may require improvements inside the cartridge I place this issue here.

**Comment by olegrok** [comment]
First of all, seems to be "kingdom.lua" should be requireable.

It allows to run it via simple script that is similar to "init.lua".

```lua
-- init_kingdom.lua
require('kingdom')
```

As bonus it allows to run some custom logic on kingdom instance (could be useful in some cases). E.g.
```lua
require('cartridge.kingdom')
setup_my_custom_options()
```


Secondly, seems that we should make kingdom.lua self-sufficient executable file (https://github.com/tarantool/cartridge/issues/711).

In case of systemd unit we should setup kingdom as separate unit. May be we should setup some default options but all need options should be set up via config file.

RPM/DEB packages deliver kingdom as part of cartridge (and I think it should not be changed now) the main goal is to make an ability to run kingdom when it needed.

cartridge-cli (https://github.com/tarantool/cartridge-cli/issues/187).
I propose to add new option "cartridge kingdom start/stop" to run "kingdom.lua".
Also we will install "init_kingdom.lua" file near "init.lua" as it was described above when user call `cartridge create`.

**Comment by olegrok** [comment]
Result of verbal discussion.

- Separate systemd unit that could be started as `systemctl start myapp@kingdom`
- Separate system config section (`instances.yml`) "myapp-kingdom". That stores config of "kingdom" application. Also we could implicitly run it if such section is specified.
- There is an opinion that kingdom could be run with `--script` option. It works but IMO looks awful.

**Comment by dokshina** [comment]
Maybe it could be like this:

* RPM/DEB will contain `myapp@.service` and `myapp.service` unit files for application intself and `myapp-kingdom` for it;
* argparse is looking for application instance configuration in `<appname>.<instance-name>` section, since `myapp-kingdom` is a separated application, I suggest placing it's config in `myapp-kingdom` section;
* for local development `cartridge start` command is used. It starts all instances described in `instances.yml` file. If it contains sections `myapp.srv-1`, `myapp.srv-2`, then `srv-1` and `srv-2` instances of `myapp` application will be started. I think, that cartridge-cli should start kingdom instance if `instances.yml` file contains `myapp-kingdom` section. 
* application entrypoint is `init.lua` by default and it can be overriden by `--script` option, we can use `init-kingdom.lua` file as a kingdom entrypoint and override it by `--kingdom-script` option.

**Comment by dokshina** [comment]
Using `stateboard` step-by-step:

### Project creation

`cartridge create` produces file `stateboard.init.lua` in the project root:

```lua
#!/usr/bin/env tarantool
require('cartridge.stateboard').cfg()
```

`instances.yml` file that contains instances configuration now contains additional section
for application stateboard:

```yaml
# instaces configuration 
<appname>.router:
  workdir: ./tmp/db_dev/3301
  advertise_uri: localhost:3301
  http_port: 8081
...

-- stateboard configuration
<appname>-stateboard:
  workdir: ./tmp/db_dev/stateboard
  listen: 3310
  password: stateboard-password
```

### Local start 

`cartridge start` works as usual: starts instances mentioned in `instances.yml`

If `--stateboard` option is passed, the `statboard` instance is started (running `stateboard.init.lua`) as well as other instances. `<appname>-stateboard` section of `instances.yml` is used to get stateboard parameters.

### RPM/DEB packages

`cartridge pack rpm|deb` produces package:

* application code is placed in `/usr/share/tarantool/<appname>` (except `stateboard.init.lua`).

* `stateboard.init.lua` is placed in `/usr/share/tarantool/<appname>-stateboard/init.lua` (since it's a separated application).

* systemd-unit for stateboard is placed in `/etc/systemd/system/<appname-stateboard>.service`. It contains explicit `Environment=TARANTOOL_APP_NAME=<appname>-stateboard`, so looks for configuration in `<appname>-stateboard` section across al files in  `/etc/tarantool/conf.d`.

* stateboard service is started by running `systemctl start <appname>-stateboard`.

I also suggest adding `--stateboard` (default=true) flag for `cartridge pack` command to disable packing stateboard files.

### Docker

# TODO

**Comment by artur-barsegyan** [comment]
@dokshina Why we need a `stateboard` parameter? 
You may just check the needed section in an `instances.yml` file and change the behavior.
