### ISSUE TITLE
Implement test for joining two instances with the same UUID

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#913]
**Problem:** what will happen to a cluster state if two instances with the same UUID will try to join a cluster?

It can be via:
- GraphQL Join operation
- simultaneous bootstrapping from snapshots of two instances with the same UUID

**Needed behavior:**
- If we already have the same UUID -> the new instance should be discarded
- If both are trying to join a cluster — move it into an error state and make it _read only_

**Comment by rosik** [comment]
1. Via graphql it's already tested:

https://github.com/tarantool/cartridge/blob/f767a9f03083ddf02f3ff62dc497a0bba30401d0/test/integration/api_join_test.lua#L82-L94

Please note that WebUI can never send such a request (WebUI never sends particular uuid, it's always generated random on backend)

2. The one with correct `advertise_uri` (according to clusterwide configuration) will be operable, the other one will be ignored by the rest of nodes. 

3. I've already mentioned it in-private, and will repeat here: uuid collision is not a problem now, because cartridge relies on `advertise_uri` more than on `uuid`. But it will become reasonable when we start working on #176. Your proposal (needed behavior) will definitely be taken into account.
